stages:
  - 🔬 Static Analysis
  - 👷 Build
  - 🤞🏼 Testing
  - 📦 Package

default:
  image: rust:1.87

🎨 cargo-fmt:
  stage: 🔬 Static Analysis
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check

📎 cargo-clippy:
  stage: 🔬 Static Analysis
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --all-features --all-targets -- --deny warnings

📦 cargo-udeps:
  stage: 🔬 Static Analysis
  before_script:
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall --no-confirm cargo-udeps
  script:
    - cargo +nightly udeps -q

🚨 cargo-audit:
  stage: 🔬 Static Analysis
  before_script:
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall --no-confirm cargo-audit
  script:
    - cargo audit -q

📈 rust-lsif:
  stage: 🔬 Static Analysis
  allow_failure: true # recommended
  before_script:
    - rustup component add rust-analyzer
  script:
    - rust-analyzer lsif . > dump.lsif
  artifacts:
    reports:
      lsif: dump.lsif

🚧 cargo-build:
  stage: 👷 Build
  script:
    - cargo build --release
  artifacts:
    expire_in: 1 day
    paths: [target]

✅ cargo-nextest:
  stage: 🤞🏼 Testing
  needs: [🚧 cargo-build]
  before_script:
    - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
  script:
    - cargo nextest run --profile ci
  artifacts:
    paths: [target/nextest/ci/junit.xml]
    reports:
      junit: target/nextest/ci/junit.xml

🐧 package:
  stage: 📦 Package
  needs:
    - 🚧 cargo-build
    - ✅ cargo-nextest
  script:
    - bash .github/scripts/create_deb.sh
  artifacts:
    paths: ["*.deb"]
