name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs: [tests]
    name: 🚧 Build
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: phantomlink
          path: target/release/phantomlink

  package:
    runs-on: ubuntu-latest
    name: 🐧 Package
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: phantomlink
      - name: Reset Rust folder structure
        run: |
          mkdir -p target/release
          mv phantomlink target/release/phantomlink
      - name: Create debian package
        run: bash ./.github/scripts/create_deb.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: phantomlink_deb
          path: "*.deb"
